#!/usr/bin/env python
"""
Bootloader Configuration Tool

This tool is responsible for configuring the bootloader after it is programmed.
"""
import argparse
import os
import serial

FILE_PATH = os.path.abspath(__file__)


def generate_secret_file():
    """
    Compile all secrets from build and configuration and store to secret file.
    """
    pass


def configure_bootloader(serial_port):
    """
    Configure bootloader using serial connection.
    """
    # If there were online configuration or checking of the bootloader using
    # the serial port it could be added here.
    pass


if __name__ == '__main__':
    # Argument parser setup.
    parser = argparse.ArgumentParser(description='Bootloader Config Tool')
    parser.add_argument('--port', help='Serial port to use for configuration.', required=True)
    args = parser.parse_args()

    # Create serial connection using specified port.
    serial_port = serial.Serial(args.port)

    # Do configuration and then close port.
    try:
        configure_bootloader(serial_port)
    finally:
        serial_port.close()

    # Generate secret file.
    generate_secret_file()

